### ISSUE TITLE
Simultaneous online users record function

### ISSUE THREAD

**Issue by GibStorm** [mewm/discord-gcpolice#1]
It would be awesome if the bot had a feature that automatically keeps tabs on how many simultaneous online users the server has, and when the record is broken, announces it to #generelt,

Also, the feature should have a !record command, that makes the bot state the record.

**Comment by mewm** [comment]
50% done. Need !record feature

**Comment by GibStorm** [comment]
Since we already have a **!record** command, maybe the command for outputting all time highest online user count should be **!peak** instead.

**Comment by mewm** [comment]
This is solved
